[project]
name = "mini-collectives"
version = "0.1.0"
description = "Educational MPI collectives from scratch with mpi4py"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mpi4py>=4.1.1",
    "numpy>=2.3.4",
]
